/*
 * sdkconfig.h
 *
 *  Created on: 31.05.2018
 *      Author: Maxi
 */

#ifndef SRC_SDKCONFIG_H_
#define SRC_SDKCONFIG_H_

//more activated stuff to make things compile
#define MBEDTLS_DHM_C

/* mbedtls_ssl_cache_x() */
#define MBEDTLS_SSL_CACHE_C
/* mbedtls_ssl_cookie_x() */
#define MBEDTLS_SSL_COOKIE_C

/*activate macros so that esp_config.h activates stuff */
#define CONFIG_MBEDTLS_HAVE_TIME
#define CONFIG_MBEDTLS_HAVE_TIME_DATE
#define CONFIG_MBEDTLS_RC4_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM
#define CONFIG_MBEDTLS_KEY_EXCHANGE_PSK
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA
#define CONFIG_MBEDTLS_TLS_ENABLED
#define CONFIG_MBEDTLS_SSL_RENEGOTIATION
//#define CONFIG_MBEDTLS_SSL_PROTO_SSL3
//#define CONFIG_MBEDTLS_SSL_PROTO_TLS1
//#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2
#define CONFIG_MBEDTLS_SSL_PROTO_DTLS
#define CONFIG_MBEDTLS_SSL_ALPN
#define CONFIG_MBEDTLS_SSL_SESSION_TICKETS
#define CONFIG_MBEDTLS_AES_C
//#define CONFIG_MBEDTLS_RC4_ENABLED_NO_DEFAULT)
//#define CONFIG_MBEDTLS_RC4_ENABLED)
#define CONFIG_MBEDTLS_BLOWFISH_C
#define CONFIG_MBEDTLS_CAMELLIA_C
#define CONFIG_MBEDTLS_CCM_C
#define CONFIG_MBEDTLS_DEBUG 1
#define CONFIG_MBEDTLS_DES_C
#define CONFIG_MBEDTLS_ECDH_C
#define CONFIG_MBEDTLS_ECDSA_C
#define CONFIG_MBEDTLS_ECP_C
#define CONFIG_MBEDTLS_GCM_C
#define CONFIG_MBEDTLS_PEM_PARSE_C
#define CONFIG_MBEDTLS_PEM_WRITE_C
#define CONFIG_MBEDTLS_RIPEMD160_C
#define CONFIG_MBEDTLS_TLS_CLIENT
#define CONFIG_MBEDTLS_TLS_SERVER
#define CONFIG_MBEDTLS_TLS_ENABLED
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C
#define CONFIG_MBEDTLS_XTEA_C
#define CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN 2048


#endif /* SRC_SDKCONFIG_H_ */
